# Generated by Django 6.0.5 on 2026-05-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField()),
                ('pokemon_name', models.CharField(max_length=100)),
                ('ability', models.CharField(max_length=100)),
                ('nature', models.CharField(max_length=100)),
                ('move1', models.CharField(max_length=100)),
                ('move2', models.CharField(max_length=100)),
                ('move3', models.CharField(max_length=100)),
                ('move4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pokemons', models.ManyToManyField(to='teams.pokemondata')),
            ],
        ),
    ]
