# Generated by Django 6.0.5 on 2026-05-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='pokemon_id',
        ),
    ]
